import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const title = "AI Work Studio: Documents";
const shortDescription = "Turn notes, photos, and files into polished documents ready to use.";

const listing = await readFile(new URL("../playstore/STORE_LISTING.md", import.meta.url), "utf8");
const checklist = await readFile(new URL("../playstore/play-console-checklist.md", import.meta.url), "utf8");

test("Play Store source files use the approved English metadata", () => {
  assert.ok(title.length <= 30, `title is ${title.length} chars`);
  assert.ok(shortDescription.length <= 80, `short description is ${shortDescription.length} chars`);
  for (const source of [listing, checklist]) {
    assert.match(source, new RegExp(title.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
    assert.match(source, new RegExp(shortDescription.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  }
});

test("canonical listing avoids unsupported or overbroad product claims", () => {
  for (const claim of ["Microsoft 365 Integration", "PDF export", "real time synchronization", "Even offline"] ) {
    assert.ok(!listing.includes(claim), `listing must not claim: ${claim}`);
  }
});

test("store narrative sells finished work rather than prompt creation", () => {
  const customerCopy = listing
    .slice(0, listing.indexOf("## Data Safety"))
    .replaceAll(/Prompt[-\s]*Lab/gi, "");
  assert.doesNotMatch(customerCopy, /\b(prompt|prompts|prompting)\b/i);
  assert.match(customerCopy, /polished documents/i);
  assert.match(customerCopy, /5 results per week/i);
  assert.match(customerCopy, /Export complete results to Word/i);
  assert.match(customerCopy, /BUAT LAPORAN DARI FOTO DAN CATATAN/i);
  assert.match(customerCopy, /RINGKAS DOKUMEN PANJANG/i);
});

test("listing documents benefit-led screenshots and the no-AAB metadata path", () => {
  assert.match(listing, /From rough input to finished work/i);
  assert.match(listing, /No new AAB required/i);
});

test("Indonesian listing fits Play's metadata limits", () => {
  const idTitle = "AI Work Studio: Dokumen AI";
  const idShort = "Ubah foto, catatan, dan file jadi laporan, ringkasan, Word, PDF, dan Excel.";
  const idSection = listing.split("## Indonesian listing (id-ID)")[1].split("## Category")[0];
  const codeBlocks = idSection
    .split("```")
    .filter((_, index) => index % 2 === 1)
    .map((value) => value.trim());
  const idLong = codeBlocks[2];
  assert.ok(idTitle.length <= 30, `id title is ${idTitle.length} chars`);
  assert.ok(idShort.length <= 80, `id short description is ${idShort.length} chars`);
  assert.ok(idLong.length <= 4000, `id full description is ${idLong.length} chars`);
  assert.ok(listing.includes(idTitle), "listing is missing the Indonesian title");
  assert.ok(listing.includes(idShort), "listing is missing the Indonesian short description");
  assert.match(idLong, /aplikasi AI pembuat laporan/i);
  assert.match(idLong, /laporan kegiatan/i);
  assert.match(idLong, /Ringkasan PDF/i);
  assert.match(idLong, /format Word/i);
  assert.match(idLong, /tabel ke Excel/i);
});

test("listing discloses AI generation and the account-free trial", () => {
  // Play expects AI-generated output to be disclosed rather than implied.
  assert.match(listing, /generated by AI and should be checked/i);
  assert.match(listing, /Hasil dibuat oleh AI/i);
  // The old listing said AI generation required an account; it no longer does.
  assert.ok(
    !listing.includes("Create a free account when you want AI generation"),
    "listing still claims AI generation requires an account"
  );
});
