import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const title = "Prompt Lab: AI Work Studio";
const shortDescription = "Turn ideas, photos, and files into finished AI drafts—prompt handled for you.";

const listing = await readFile(new URL("../playstore/STORE_LISTING.md", import.meta.url), "utf8");
const checklist = await readFile(new URL("../playstore/play-console-checklist.md", import.meta.url), "utf8");

test("Play Store source files use the approved English metadata", () => {
  assert.ok(title.length <= 30, `title is ${title.length} chars`);
  assert.ok(shortDescription.length <= 80, `short description is ${shortDescription.length} chars`);
  for (const source of [listing, checklist]) {
    assert.match(source, new RegExp(title.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
    assert.match(source, new RegExp(shortDescription.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")));
  }
});

test("canonical listing avoids unsupported or overbroad product claims", () => {
  for (const claim of ["Microsoft 365 Integration", "PDF export", "real time synchronization", "Even offline"] ) {
    assert.ok(!listing.includes(claim), `listing must not claim: ${claim}`);
  }
});

test("listing documents benefit-led screenshots and the no-AAB metadata path", () => {
  assert.match(listing, /From rough input to a finished AI draft/);
  assert.match(listing, /No new AAB required/i);
});

test("Indonesian listing fits Play's metadata limits", () => {
  const idTitle = "Prompt Lab: Studio Kerja AI";
  const idShort = "Ubah ide, foto, dan file langsung jadi hasil kerja AI yang siap dilanjutkan.";
  assert.ok(idTitle.length <= 30, `id title is ${idTitle.length} chars`);
  assert.ok(idShort.length <= 80, `id short description is ${idShort.length} chars`);
  assert.ok(listing.includes(idTitle), "listing is missing the Indonesian title");
  assert.ok(listing.includes(idShort), "listing is missing the Indonesian short description");
});

test("listing discloses AI generation and the account-free trial", () => {
  // Play expects AI-generated output to be disclosed rather than implied.
  assert.match(listing, /generated by AI and should be checked/i);
  assert.match(listing, /Hasil dibuat oleh AI/i);
  // The old listing said AI generation required an account; it no longer does.
  assert.ok(
    !listing.includes("Create a free account when you want AI generation"),
    "listing still claims AI generation requires an account"
  );
});
