import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const read = (relative) => readFile(new URL(relative, import.meta.url), "utf8");

const mainSource = await read("../src/main.jsx");
const shellSource = await read("../src/ui/Shell.jsx");
const composerSource = await read("../src/ui/Composer.jsx");
const resultSource = await read("../src/ui/Result.jsx");
const compareSource = await read("../src/ui/Compare.jsx");
const accountSource = await read("../src/ui/Account.jsx");
const sheetSource = await read("../src/ui/Sheet.jsx");
const adminSource = await read("../src/admin/AdminConsole.jsx");
const baseCss = await read("../src/ui/base.css");
const tokensCss = await read("../src/ui/tokens.css");
const i18nSource = await read("../src/ui/i18n.js");

test("readiness is presented as an estimate, never as a guarantee", () => {
  assert.match(resultSource, /result\.readiness/);
  assert.match(resultSource, /result\.readinessHelp/);
  // Both languages must disclaim it.
  assert.match(i18nSource, /automated score, not a quality guarantee/i);
  assert.match(i18nSource, /penilaian otomatis, bukan jaminan kualitas/i);
});

test("local compare fallback keeps measured dimensions and is not labelled as provider scoring", () => {
  assert.match(mainSource, /constraints: scoreA\.constraints/);
  assert.match(mainSource, /risk: scoreA\.risk/);
  assert.doesNotMatch(mainSource, /constraints: Math\.max\(40/);
});

test("compare states whether the score came from a model or from local heuristics", () => {
  assert.match(compareSource, /getCompareEvaluationMeta/);
  assert.match(compareSource, /compare\.heuristicNote/);
  assert.match(compareSource, /compare\.providerNote/);
});

test("AI output carries a visible generated-by-AI notice", () => {
  assert.match(resultSource, /result\.aiNotice/);
  assert.match(i18nSource, /Generated by AI\. Check it before you use or send it\./);
  assert.match(i18nSource, /Dibuat oleh AI\. Periksa kembali sebelum dipakai atau dikirim\./);
});

test("the shell is a single canvas with no tab bar", () => {
  assert.doesNotMatch(shellSource, /bottom-nav/);
  assert.doesNotMatch(mainSource, /v2-bottom-nav/);
  // History and Account are the only chrome destinations, and both are labelled.
  assert.match(shellSource, /aria-label=\{t\("nav\.history"\)\}/);
  assert.match(shellSource, /aria-label=\{t\("nav\.account"\)\}/);
});

test("a skip link precedes the main landmark", () => {
  assert.match(shellSource, /className="pl-skip" href="#pl-main"/);
  assert.match(shellSource, /<main className="pl-main" id="pl-main">/);
  assert.match(baseCss, /\.pl-skip/);
});

test("the request textarea is programmatically labelled", () => {
  assert.match(composerSource, /<label className="pl-composer-label" htmlFor=\{requestId\}>/);
  assert.match(composerSource, /<textarea\s+id=\{requestId\}/);
});

test("every advanced select is labelled and keeps canonical English values", () => {
  assert.match(composerSource, /<label className="pl-label" htmlFor=\{id\}>/);
  assert.match(composerSource, /<select\s+id=\{id\}/);
  // Values come from the shared options module, not from translated labels.
  assert.match(composerSource, /from "\.\/options\.js"/);
  assert.match(composerSource, /translateOption\(option\)/);
});

test("the file input stays keyboard reachable", () => {
  // Hiding the input with display:none would remove it from the tab order; it
  // is made transparent and overlaid on the styled label instead.
  assert.match(composerSource, /<input\s+type="file"/);
  assert.doesNotMatch(composerSource, /type="file"[\s\S]{0,200}display:\s*none/);
});

test("segmented controls expose their pressed state", () => {
  assert.match(accountSource, /aria-pressed=\{lang === item\.code\}/);
  assert.match(accountSource, /aria-pressed=\{themeMode === value\}/);
});

test("sheets are modal, labelled, focus-trapping, and restore focus", () => {
  assert.match(sheetSource, /role="dialog"/);
  assert.match(sheetSource, /aria-modal="true"/);
  assert.match(sheetSource, /aria-labelledby=\{titleId\}/);
  assert.match(sheetSource, /event\.key === "Escape"/);
  assert.match(sheetSource, /event\.key !== "Tab"/);
  assert.match(sheetSource, /restoreRef\.current/);
});

test("admin tab controls still identify their tabs and panels", () => {
  assert.match(adminSource, /role="tab"[\s\S]*?aria-selected=/);
  assert.match(adminSource, /aria-controls=\{`admin-panel-/);
  assert.match(adminSource, /role="tabpanel"[\s\S]*?id=\{`admin-panel-/);
});

test("interactive controls have a visible keyboard focus treatment", () => {
  assert.match(baseCss, /:focus-visible/);
  assert.match(baseCss, /outline:\s*2px solid var\(--focus\)/);
});

test("light is the default scheme and dark requires an explicit choice", () => {
  assert.doesNotMatch(tokensCss, /@media \(prefers-color-scheme: dark\)/);
  assert.match(tokensCss, /:root\[data-ui-theme="dark"\]/);
  assert.match(tokensCss, /color-scheme: light/);
});

test("reduced motion is honoured", () => {
  assert.match(baseCss, /@media \(prefers-reduced-motion: reduce\)/);
});

test("no render-blocking web font is imported", () => {
  assert.doesNotMatch(baseCss, /fonts\.googleapis\.com/);
  assert.doesNotMatch(tokensCss, /fonts\.googleapis\.com/);
});
